services:
    rabbitmq:
      container_name: ec-rabbitmq
      ports:
          - "15672:15672"
          - "5672:5672"
      image: "rabbitmq:3.13.6-management"
    mongo:
      container_name: ec-mongo
      ports:
          - "27017:27017"
      image: "mongo:4.0.18-xenial"
    redis:
      container_name: ec-redis
      ports:
          - "6379:6379"
      image: "redis:5.0.9-buster"
    fluent: 
      container_name: ec-fluent
      build:
        context: https://raw.githubusercontent.com/nmarsollier/ecommerce/master/fluent/Dockerfile
      ports:
          - "24224:24224"
    prod-auth-go:
      build:
          context: https://raw.githubusercontent.com/nmarsollier/authgo/master/Dockerfile.prod
      # container_name: prod-auth-go
      ports:
          - '3000:3000'
      image: prod-auth-go
      depends_on:
          - "rabbitmq"
          - "mongo"
    prod-image-go:
      container_name: prod-image-go
      build:
          context: https://raw.githubusercontent.com/nmarsollier/imagego/master/Dockerfile.prod
      ports:
          - '3001:3001'
      # image: prod-image-go
      depends_on:
          - "rabbitmq"
          - "redis"
    prod-catalog-go:
      container_name: prod-catalog-go
      build:
          context: https://raw.githubusercontent.com/nmarsollier/cataloggo/master/Dockerfile.prod
      ports:
          - '3002:3002'
      # image: prod-catalog-go
      depends_on:
          - "rabbitmq"
          - "mongo"
    prod-cart-go:
      container_name: prod-cart-go
      build:
          context: https://raw.githubusercontent.com/nmarsollier/cartgo/master/Dockerfile.prod
      ports:
          - '3003:3003'
      # image: prod-cart-go
      depends_on:
          - "rabbitmq"
          - "mongo"
    prod-orders-go:
      container_name: prod-orders-go
      build:
          context: https://raw.githubusercontent.com/nmarsollier/ordersgo/master/Dockerfile.prod
      ports:
          - '3004:3004'
      # image: prod-orders-go
      depends_on:
          - "rabbitmq"
          - "mongo"
    # prod-api-cli:
    #   container_name: prod-api-cli
    #   build:
    #       context: "https://raw.githubusercontent.com/nmarsollier/ecommerce_api_client_react/master/Dockerfile.prod"
    #   ports:
    #       - '4200:80'
    #   # image: prod-api-cli
    #   stdin_open: true
    #   depends_on:
    #       - "prod-orders-go"
    #       - "prod-cart-go"
    #       - "prod-catalog-go"
    #       - "prod-image-go"
    #       - "prod-auth-go"

# networks:
#   default:
#     driver: bridge